### ISSUE TITLE
Consider adding recent paper "Breaking the Limit of Graph Neural Networks by Improving the Assortativity of Graphs with Local Mixing Patterns"

### ISSUE THREAD

**Issue by susheels** [mengliu1998/DL4DisassortativeGraphs#2]
From KDD '21 (https://dl.acm.org/doi/abs/10.1145/3447548.3467373) 
CODE: https://github.com/susheels/gnns-and-local-assortativity

**Comment by mengliu1998** [comment]
Hi @susheels,

Thank you for the suggestion. I have added this paper to the repo. Please feel free to submit PRs if you have interesting suggested papers in the future. Thank you.
