### ISSUE TITLE
A new paper is accepted in NIPS21

### ISSUE THREAD

**Issue by yeonjun-in** [mengliu1998/DL4DisassortativeGraphs#3]
code: https://github.com/jindi-tju/U-GCN
paper: https://papers.nips.cc/paper/2021/file/5857d68cd9280bc98d079fa912fd6740-Paper.pdf

**Comment by mengliu1998** [comment]
@yeonjun-in,

Sorry for the late reply. Could you submit a PR for this paper?

Thank you for your contribution.

**Comment by mengliu1998** [comment]
@yeonjun-in,

I just added this paper. Thank you for letting me know.
